# Linear Algebra Refresher

- Vector operations
- Multiplication
-- Vector-vector multiplication
-- Matrix-vector multiplication
-- Matrix-matrix multiplication
- Identity matrix
- Inverse

## Vector operations

In [2]:
import numpy as np

In [4]:
u = np.array([2, 4, 5, 6])
2 * u

array([ 4,  8, 10, 12])

### Vector addition

In [5]:
v = np.array([1, 0, 0, 2])
u + v

array([3, 4, 5, 8])

### Multiplication

In [4]:
u * v

array([ 2,  0,  0, 12])

Dot product: multiply each element of u with the corresponding element of v, and then we sum the results

In [5]:
u.dot(v)


np.int64(14)

Matrix-vector multiplication

In [3]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [7]:
U.shape

(3, 4)

In [8]:
u.dot(v)

np.int64(14)

In [9]:
U.dot(v)

array([14,  5,  5])

In [10]:
u * v

array([ 2,  0,  0, 12])

In [11]:
v2 = np.array([1, 0.5, 2, 1])

In [12]:
U.dot(v2)

array([20. ,  6. ,  8.5])

Matrix-matrix multiplication

In [3]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [5]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity matrix
The identity matrix is useful for explaining what a matrix inverse is

In [6]:
I = np.eye(3)

In [7]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Inverse
The inverse of A, usually written A⁻¹, is a matrix such that when we multiply it by A, we get I

In [4]:
Vs = V[[0, 1, 2]]

In [10]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [5]:
Vs_inv = np.linalg.inv(Vs)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

In [6]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [7]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])